install:
  - ps: Install-Product node 8.2.1 x64
  - node --version
  - npm --version

before_build:
  - npm install
  - npm prune
  - npm run rebuild

build_script:
  - npm run lint
  - npm run dist

test: off

cache:
  - node_modules
  - '%localappdata%\electron'
  - '%localappdata%\electron-builder'
