install:
  - ps: Install-Product node 7.9.0 x64
  - node --version
  - npm --version

before_build:
  - npm install

build_script:
  - npm test
  - npm run dist:win

test: off

cache:
  - node_modules
  - '%APPDATA%\Local\electron'
  - '%APPDATA%\Local\electron-builder'
