install:
  - ps: Install-Product node 7.9.0 x64
  - node --version
  - npm --version

before_build:
  - npm install
  - npm run rebuild

build_script:
  - npm test
  - npm run dist:win

test: off

cache:
  - node_modules
  - '%localappdata%\electron'
  - '%localappdata%\electron-builder'
